name: PR Web Application Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-application-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - name: install pnpm
        run: npm install -g pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: run unit tests
        run: pnpm test:unit
